# Generated by Django 4.2.4 on 2023-08-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='details',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
